name: Distributed XGBoost with Dask on CML
description: >-
    Demonstrates a typical data science workflow for developing a credit card fraud
    application including how to train a distributed XGBoost model using Dask on CML workers.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2022-07-30"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_deps
    script: scripts/install_dependencies.py
    arguments: None
    cpu: 1
    memory: 2
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_deps
    short_summary: Running install dependencies job.
    long_summary: >-
      Running the job to install dependencies.



